config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :home, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :teams do
    resources :users
    resources :tasks do
      member do
        get 'unassign'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :stage, presence: true
  belongs_to :user
  belongs_to :team

  LEVELS = ['Новичек', 'Середнячек', 'Мастер'].freeze

  def self.levels
    LEVELS
  end
end

app/models/team.rb
class Team < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :tasks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    has_and_belongs_to_many :teams
    def self.from_omniauth(auth)
      where(email: auth.info.email).first_or_create do |user|
        user.email = auth.info.email
        user.name = auth.info.name 
        user.user_id = auth.info.user_id  
        team = Team.find_or_create_by(slack_id: auth.info.team_id) 
        team.update(title: auth[:extra][:team_info][:team][:name])
        user.teams << team unless user.teams.where(slack_id: auth.info.team_id).any?
      end
    end
    devise :omniauthable, omniauth_providers: %i[slack]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
  def user_required
    if !user_signed_in?
     redirect_to user_slack_omniauth_authorize_path
    end
   end

   def team_required
    redirect_to user_slack_omniauth_authorize_path unless current_user
    @team = current_user.teams.find_by(id: (params[:team_id] || params[:id]))
    redirect_to user_slack_omniauth_authorize_path unless @team
   end

  def set_team_id
    @team = Team.find(params[:team_id])
  end

  def set_teams
    @teams = current_user.teams
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        flash[:notice] = "something go wrong, please sign in"
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def slack
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, kind: "slack") if is_navigational_format?
        else
            session["devise.slack_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
            p request.env["omniauth.auth"]
    end
          
    def failure
        redirect_to home_index_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :user_required
  before_action :set_team_id
  before_action :set_teams
  before_action :set_task, only: [:show, :edit, :update, :destroy, :unassign]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @team.tasks
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = @team.tasks.create(task_params)

    if @task.save
      redirect_to team_tasks_path(@team), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to [@team, @task], notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to team_tasks_path(@team), notice: 'Task was successfully destroyed.'
  end
  
  def unassign
    @task.update(user: nil)
    redirect_to [@team, @task], notice: 'Task was successfully unassigned.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @team.tasks.find(params[:id])
    end    
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :stage, :level, :score, :team_id, :user_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :user_required
  before_action :team_required, only: [:show]
  before_action :set_teams
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    if @team.update(team_params)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:title, :slack_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :user_required
  before_action :set_team_id
  before_action :set_teams
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = @team.users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = @team.users.create(user_params)

    if @user.save
      redirect_to team_users_path(@team), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to [@team,@user], notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to team_users_path(@team), notice: 'User was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = @team.users.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :email, :level, :name, :user_id, :team_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  before_action :user_required
  before_action :set_teams
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= link_to "Sign in with Slack", user_slack_omniauth_authorize_path, :class => "btn btn-link"%>
<%= link_to "Teams", teams_path, :class => "btn btn-link"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RocketTeamCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Choose team</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
   <ul class="navbar-nav">
    <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Teams
     </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if @teams.each do |team| %>
          <a class="dropdown-item" <%= link_to team.title, team %></a>
        <% end %>
        <% end %>
      </div>
     </li>
   </ul>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for [@team, @task], :html => { :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :stage, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :stage, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <%= f.select :level,  options_for_select(Task.levels), {}, :class => 'form-control' %>  
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <%= f.select :user_id,  options_from_collection_for_select(User.all, 'id', 'name'), {}, :class => 'form-control' %>  
    </div>
  </div>
  <div class="form-group">
    <%= f.label :score, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :score, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                team_tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:stage) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, team_task_path(@team, task) %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.stage %></td>
        <td><%= task.level %></td>
        <td><%= task.score %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      team_task_path(@team, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_team_task_path(@team, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      team_task_path(@team, task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_team_task_path(@team),
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @task.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stage) %>:</strong></dt>
  <dd><%= @task.stage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @task.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score) %>:</strong></dt>
  <dd><%= @task.score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user) %>:</strong></dt>
  <% if @task.user %>
    <dd><%= link_to @task.user.name, [@team, @task.user] %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              team_tasks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_team_task_path(@task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              team_task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_for [@team,@user], :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <%= f.select :level,  options_for_select(Task.levels), {}, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                team_users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
<%= link_to "Sign in with Slack", user_slack_omniauth_authorize_path, :class => "btn btn-link"%>

</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, team_user_path(@team, user) %></td>
        <td><%= user.title %></td>
        <td><%= user.email %></td>
        <td><%= user.level %></td>
        <td><%= user.user_id %></td>
        <td><%= user.name %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
          team_user_path(@team, user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_team_user_path(@team, user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      team_user_path(@team, user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_team_user_path(@team),
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @user.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @user.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @user.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              team_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_team_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              team_user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


<h1>User Tasks</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Task.human_attribute_name(:id) %></th>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:description) %></th>
      <th><%= Task.human_attribute_name(:stage) %></th>
      <th><%= Task.human_attribute_name(:level) %></th>
      <th><%= Task.human_attribute_name(:name) %></th>
      <th><%= Task.human_attribute_name(:user_id) %></th>
      <th><%= Task.human_attribute_name(:score) %></th>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
  </table>
    <% @user.tasks.each do |task| %>
      <tr>
      <table class="table table-striped">
        <td><%= link_to task.id, team_task_path(@team, task) %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.stage %></td>
        <td><%= task.level %></td>
        <td><%= task.score %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      team_task_path(@team, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_team_task_path(@team, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'unassign', 
                      unassign_team_task_path(task),
                      :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>    
      </table>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<%= link_to "Sign in with Slack", user_slack_omniauth_authorize_path, :class => "btn btn-link"%>